name: Build Homebrew package
on:
  push:
    paths:
      - .github/workflows/build-pkg.yml
      - package/scripts
  release:
    types:
      - published

jobs:
  build:
    runs-on: macos-12
    env:
      IDENTIFIER: sh.brew.Homebrew
      TMP_PATH: /tmp/brew
      MIN_OS: '11.0'
      # Please replace with your team ID.
      # https://developer.apple.com/help/account/manage-your-team/locate-your-team-id/
      SIGNING_IDENTITY: '***'
    steps:
      - uses: actions/checkout@v3
        with:
          path: brew
          fetch-depth: 0
      - name: Version name
        id: print-version
        run: |
          echo "version=$(git -C brew describe --tags --always)" > $GITHUB_OUTPUT
      - name: Install the Apple certificate
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          
          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          
          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
      - name: Build package
        run: |
         pkgbuild --root brew \
                  --scripts brew/package/scripts \
                  --install-location "$TMP_PATH" \
                  --identifier "$IDENTIFIER" \
                  --sign "$SIGNING_IDENTITY" \
                  --min-os-version "$MIN_OS" \
                  --filter .DS_Store \
                  --version ${{ steps.print-version.outputs.version }} \
                  Homebrew-${{ steps.print-version.outputs.version }}.pkg
      - uses: actions/upload-artifact@v3
        with:
          name: Homebrew ${{ steps.print-version.outputs.version }}
          path: Homebrew-${{ steps.print-version.outputs.version }}.pkg
